#!/usr/bin/env node
const fs = require('fs')
const html5Lint = require('html5-lint')

fs.readFile('index.html', 'utf8', function (error, html) {
  if (error) throw error
  html5Lint(html, function (error, results) {
    if (error) throw error
    results.messages.forEach(function (message) {
      console.log('HTML5 Lint [%s]: %s', message.type, message.message)
    })
  })
})
